### ISSUE TITLE
Document relationship between xmldom and standard Web APIs

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#119]
`xmldom` seems to be like a "ponyfill" ([[1]](https://github.com/sindresorhus/ponyfill), [[2]](https://ponyfoo.com/articles/polyfills-or-ponyfills)) for some standard Web APIs

I really like the arguments for "ponyfill" and would favor documenting this.

[1] https://github.com/sindresorhus/ponyfill
[2] https://ponyfoo.com/articles/polyfills-or-ponyfills

**Comment by karfau** [comment]
Related: #176

**Comment by rooby** [comment]
This would be very useful. As it is, it's pretty confusing that this just appears to replicate a standard API and the docs make no mention of it or why you should or shouldn't use this instead of the API.

**Comment by karfau** [comment]
@rooby Sorry for the late reply.
I agree that the documentation is not very clear about how far xmldom covers which spec, or how it relates to those specs.

But I'm quite certain about this aspect:
> and the docs make no mention of it or why you should or shouldn't use this instead of the API.

I would think it only makes sense to use xmldom over the native API, if you need to be able to deal with XML **outside** of browser (runtimes).
One could even only use xmldom in a code base, if the APIs it mimics are not available, but this of course bears the risk that the code behaves differently between different runtimes, just because xmldom implements things slightly different than the browsers do.

I added some more information as part of #211, please have a look and comment if you think something is missing or not clear.
