### ISSUE TITLE
Inconsistent attribute quote handling

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#125]
I discovered this in a custom `assert.skip` call in `test/html/normalize.test.js`.

`new DOMParser().parseFromString('<r><Label onClick="doClick..>Hello, World</Label></r>','text/html')` (missing end quote in `onClick` attribute) leads to this with `&lt;`:

```
<r xmlns="http://www.w3.org/1999/xhtml">&lt;Label onClick="doClick..>Hello, World</r>
```

while `new DOMParser().parseFromString('<Label onClick=doClick..">Hello, World</Label>','text/html')` leads to this (looks correct):

```
<Label onClick="doClick.." xmlns="http://www.w3.org/1999/xhtml">Hello, World</Label>
```

**Comment by karfau** [comment]
Maybe it makes sense to label issues related to invalid (or even not well formed) XML as such, so that it's also more clear how important they are. (I would argue that issues with valid or well formed XML are more severe.)

**Comment by karfau** [comment]
Just for later reference, this is what Chrome does with the first input you provided:
![image](https://user-images.githubusercontent.com/135657/131795153-43456bd8-72c8-44b9-b82e-91269b7f56a0.png)
So in HTML mode the content of the `r` tag is discarded (most likely due to it not being wellformed?) and in XML an error is reported.
