### ISSUE TITLE
Conflicting license versions used for LGPL option

### ISSUE THREAD

**Issue by j-buckland** [xmldom/xmldom#172]
The [package.json](https://github.com/xmldom/xmldom/blob/master/package.json#L93) states that the LGPL license version applicable to this project is version 2.

The [LICENSE.md](https://github.com/xmldom/xmldom/blob/master/LICENSE.md) file links to the LGPL version 3 license (link leads through to [here](http://www.gnu.org/licenses/lgpl-3.0.html)).

These license versions differ in content. I can recommend using https://spdx.org/licenses/ and the short identifier to identify which license version you were intending to use.

(I'm aware that there is a choice between this and the MIT license (which is more permissive), so I'm not sure how many people will be impacted)

**Comment by karfau** [comment]
Thx for making us aware, I did some research:

Even though the LICENSE.MD file doesn't mention any version explicitly, when the link was added ( afbf555e1b91179d3292fd6f46233799b541f044 on Sep 10, 2013) it already [pointed at v3](https://web.archive.org/web/20130908085858/http://www.gnu.org/licenses/lgpl.html)

`v2` was only added to `package.json` as part of b7fd801dbff3f3d05a0d3f4fe3c2f0ef0f3f344f on Aug 17, 2016. (Before that the package json was in sync with the LICENSE file.)

It's worth mentioning that the readme (and this way also the page in npm) has a badge that mentions v2 (since f4ba214e71967565dd81059572691c68a7f4de23 on Jul 1, 2020) which shields.io seems to derive from the package.json file.

So it looks like to original intention was to point to v3, although the package json was changed to v2 already in the old project location.

Here is some comparison between the two: https://softwareengineering.stackexchange.com/questions/189668/lgpl-2-1-vs-lgpl-3-0-advantages-and-disadvantages#189692


As soon as @brodybits and @kethinov came to a conclusion which one it should be, we can fix it.

**Comment by karfau** [comment]
PS: I'm totally unable to judge if it would be possible to switch to MIT only in the way that the fork took place and whether that would exclude anybody. But since v2 and v3 are incompatible and @j-buckland is the first to mention that we have inconsistent information in the repo, it might be worth to reconsider such a step.

**Comment by brodybits** [comment]
Hello I just updated the title for the sake of clarity.

Considering that both the original `LICENSE` file and `package.json` had MIT as a license option, I cannot see any reason we we cannot drop the LGPL license option, which I would definitely favor.

**Comment by timbru31** [comment]
If in case the project was dual licensed I think we can easily drop one of the licenses. 

In my, non lawyer, opinion it would require all contributors to be fine with a license change (but luckily this doesn’t apply)

While GPL is great of OSS, it’s a PITA for commercial and closed source projects.

Therefore, I’m +1 on only offering MIT.
