### ISSUE TITLE
Incorrect serialization of XML attributes containing white space

### ISSUE THREAD

**Issue by marrus-sh** [xmldom/xmldom#284]
The code for serializing attributes (here: <https://github.com/xmldom/xmldom/blob/6ce470094c7ea78baa4e5ea18e912a88cd11a63c/lib/dom.js#L1138-L1140>) does not treat newlines in any special way.

This is a problem, because XML parses literal newlines as spaces. However, it allows newlines in attributes when they are provided as character references. (See: <https://www.w3.org/TR/xml/#AVNormalize>.)

So:

```xml
<element attribute="with&#xA;newline"></element>
```

serializes as

```xml
<element attribute="with
newline"></element>
```

which then gets parsed as

```xml
<element attribute="with newline"></element>
```

which is not equivalent.

**Comment by marrus-sh** [comment]
(for reference, the affected characters which need to be escaped in attributes are `&#x9;`, `&#xA;`, and `&#xD;`; see, for example, <https://www.w3.org/TR/xml-c14n11/#ProcessingModel>)

**Comment by marrus-sh** [comment]
update: this is an open specification bug in DOM Parsing: https://github.com/w3c/DOM-Parsing/issues/59

**Comment by karfau** [comment]
@marrus-sh Thank you for reporting this, especially for finding and referencing the specification bug.

I believe that the fix needs to be applied at least to the parsing side. But maybe also to the serialization part that you linked, but I'm not sure about it.

I'm not sure how soon I will be able to address it, even though I'm very curious to see the failing tests.

Is there any workaround for this that you are aware of?

**Comment by karfau** [comment]
Just out of curiosity I started digging a bit.

I finally understood why you are pointing at the serializer: By checking the (Chrome and Firefox) browser implementations I found out that the value we are currently having in the DOM is correct (`\n`) in the example you provided, but it's not converted back to the entity reference when it's serialized.

There is the following problem: Since xmldom is currently not taking care of normalizing line endings and is only taking care of replacing character references with their literal values (instead of doing everything described in https://www.w3.org/TR/xml/#AVNormalize), just converting literal characters in the DOM back to the character references will also convert literal input to character references, even though they should be converted to spaces.

I'm not sure if this is a huge issue, the snapshot tests that need to be updated when adding the fix look better then before from my perspective:

https://github.com/xmldom/xmldom/compare/master...karfau:284-serialize-whitespace-literals-to-character-references

Any opinions?

**Comment by marrus-sh** [comment]
this definitely looks closer to expected output!

i might not be understanding the code correctly, but i think if you add a `.replace(/[\t\n\r]/g, " ")` to <https://github.com/xmldom/xmldom/blob/621fad87c109b2682034431d1937d1bf80fc25ae/lib/sax.js#L265> *before* the `entityReplacer`, it should handle the attribute normalization on parsing well enough? [you want to replace literal tabs/newlines/etc with spaces, but not character references.]

**Comment by karfau** [comment]
Yes, I already looked at that place in the code before, it's not the only line where this replacement took place, but I moved it into one place and added the replacement of white space literals.

I still need to figure out if this needs to be considered a breaking change, that's why the PR is only a draft for now.

**Comment by marrus-sh** [comment]
this looks perfect, thank you!! no worries about it not landing right away; i’m just glad it’s getting fixed
