### ISSUE TITLE
standard(ize) source code formatting

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#29]
from review of pr #28 I discovered that code is sometimes indented with only tabs and sometimes with a combination of tabs and spaces. Also at least one occasion of code with no semicolon.

Most drastic would be to use `standard`, `semistandard`, or `prettier-standard` to reformat the code in what I think is a nicer style. (`prettier-standard` actually uses the `prettierx` fork of Prettier that is maintained by myself, which could be seen as an advantage or perhaps even a disadvantage)

Less drastic would be to apply some simplistic rules such as only indent with tabs and always use semicolons to achieve better consistency with minimal code churn. I think it should be possible to do this with custom eslint rule configuration.

**Comment by kethinov** [comment]
I personally use `standard` on my other projects. I almost threw it into that PR but it would've been an epic diff.

**Comment by awwright** [comment]
I'd like to submit a PR for an `.eslintrc.js` file, and an `.editorconfig` file, but it'd probably be a good idea to figure some things out first...

Since there doesn't really seem to be a standard, it might be a good idea to not convert everything all at once... I'm playing around with a PR for a bare-minimum `.eslintrc.js` file for obvious problems; and then you can add code style preferences later.

For indents, my vote would be to keep tabs. Not to rehash the tabs v. spaces holy war or anything, but I like customizing my indent size, and I like it when you can't accidentally highlight half an indent (as an example: lib/entities.js is indented 7 spaces).

Thoughts?
