### ISSUE TITLE
Document how to access possible values for `Node.nodeType`

### ISSUE THREAD

**Issue by pyrsmk** [xmldom/xmldom#351]
Testing nodes for their types is a fairly common task so it would be more practical to access to NodeType constants instead of dealing with integers (which are not documented). Here's an example of what I want to do: 

```js
const { DOMParser, NodeType } = require('@xmldom/xmldom')

const xml = new DOMParser().parseFromString(contents)
const rows = Array.from(xml.childNodes[2].childNodes).filter(node => node.nodeType == NodeType.ELEMENT_NODE)
```

**Comment by karfau** [comment]
Hey thank you for reporting this.
You are right we are missing documentation here.

The good news is: The information is already exported, the bad new is it's not part of the top level export.

According to DOMLevel 2 (and above), the values of `Node.nodeType` are declared on `Node`, so it's `Node.ELEMENT_TYPE` instead of `NodeType.ELEMENT_TYPE`.

There are two ways to get access to the possible values of `node.nodeType`:

## Use the `Node` prototype (should be preferred and documented)

If you have a `Node` instance use the values from it's prototype:
```
const { DOMParser, NodeType } = require('@xmldom/xmldom')

const xml = new DOMParser().parseFromString(contents)
const rows = Array.from(xml.childNodes[2].childNodes).filter(node => node.nodeType == node.ELEMENT_NODE)
```
I just checked, this also works in the browser, so it seems to be spec compliant.

## Import the `Node` type
To get access to `Node` implemented by xmldom you have to import it like this:
```js
const { Node } = require('@xmldom/xmldom/lib/dom');
```
or in typescript
```js
import { Node } = from '@xmldom/xmldom/lib/dom';
```
although I didn't check if typescript will complain about missing types when doing that.

We are currently not exporting the DOM types beside `DOMImplementation` as part of the main export, since this provides access to the constructor functions, which are not part of the spec and should not be used directly (Throws error about illegal constructor in the browser, but doesn't in xmldom). Treat this with care, since it's "internal API" of xmldom and we are able to break this in any version we want.

I'm leaving this issue open so we can take care of documenting this better and providing types if they are missing.

**Comment by pyrsmk** [comment]
Thanks a lot for your exhaustive comment on the subject ❤️
