### ISSUE TITLE
Parsing with type `text/html` leads to unwanted default namespace 

### ISSUE THREAD

**Issue by sdeprez** [xmldom/xmldom#377]
Hi!

When using `DOMParser` with mime type `text/html`, the parser adds the default namespace `http://www.w3.org/1999/xhtml`, because of [this line of code](https://github.com/xmldom/xmldom/blob/6d0bc6cad75ad98f6d04929dcee747fc425ef4a7/lib/dom-parser.js#L26). It looks like it's expected, because there is even [a test for it](https://github.com/xmldom/xmldom/blob/dc429ae2ebd09e2fa3380c4a9b292d1164898f02/test/dom-parser.test.js#L31) but in my opinion, it's quite surprising and make simple xpath queries fail, example using [xpath library](https://github.com/goto100/xpath):

```javascript
const doc = (new DOMParser()).parseFromString('<input value="abc">', 'text/html');
xpath.evaluate('//input', doc, null, 0, null); // No results
```
I know I could use `local-name` but in that case, I don't control the xpath, so what's the rationale of adding this default namespace? Can we opt-out of that behaviour?

As a current workaround, I did this to pass a `xmlns` object with a setter ignoring the update of `''` key. It works, but it's obviously quite brittle and hacky.
```javascript
const xmlns={set [''] (_) {}}
const doc = (new DOMParser({xmlns})).parseFromString('<input value="abc">', 'text/html');
xpath.evaluate('//input', doc, null, 0, null); // 1 result
```

**Comment by karfau** [comment]
Thank you for reporting this.

I don't have a lot of experience regarding xpath, but this is what I found out:

According to https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate the code you provided should find something, if it works the same way as the browser. I created the linked stackblitz to reproduce it and am able to verify that the xpath library is not able to find anything (output 4).

https://stackblitz.com/edit/js-xmldom359-fd3yir?devtoolsheight=33&file=index.js
```javascript
import xmldom from '@xmldom/xmldom';
import xpath from 'xpath';
// See https://github.com/xmldom/xmldom/issues/377
const source = `<input value="abc">`;

const doc = new DOMParser().parseFromString(source, 'text/html');
console.log(
  '1. The namespace of the input element in the browser API to parse source',
  doc.getElementsByTagName('input')[0].namespaceURI
);
const xmldomDoc = new xmldom.DOMParser().parseFromString(source, 'text/html');
console.log(
  '2. The namespace of the input element when using @xmldom/xmldom to parse source',
  xmldomDoc.getElementsByTagName('input')[0].namespaceURI
);

let browserXPathResult = doc.evaluate('//input', doc, null, 0, null);
console.log(
  '3. The xpath result when using the browser API',
  browserXPathResult.iterateNext()
);
let xpathResult = xpath.evaluate('//input', doc, null, 0, null);
console.log(
  '4. The xpath result when using the xpath lib',
  xpathResult.iterateNext()
);
```

![image](https://user-images.githubusercontent.com/135657/154143808-6d48b01a-4484-4b66-99fb-ee828e3f50e0.png)

I disagree that this is because of the namespace added by xmldom (output 2) though, since the namespace is also present when the browser parses the snippet you provide (output 1). Using the browser API to `evaluate` your xpath also works as described in the MDN docs (output 3).

And I also found the related specs, that state that this is the expected behavior:
https://html.spec.whatwg.org/#interactions-with-xpath-and-xslt
> [...]
> If the context node is from an HTML DOM, the default element namespace is "http://www.w3.org/1999/xhtml".
> [...]
> This is equivalent to adding the default element namespace feature of XPath 2.0 to XPath 1.0, and using the HTML namespace as the default element namespace for HTML documents. It is motivated by the desire to have implementations be compatible with legacy HTML content while still supporting the changes that this specification introduces to HTML regarding the namespace used for HTML elements, and by the desire to use XPath 1.0 rather than XPath 2.0.
> 
> This change is a [willful violation](https://html.spec.whatwg.org/#willful-violation) of the XPath 1.0 specification, motivated by desire to have implementations be compatible with legacy content while still supporting the changes that this specification introduces to HTML regarding which namespace is used for HTML elements.

The DOM specification also has someplaces related to that:
- https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument
- https://dom.spec.whatwg.org/#dom-domimplementation-createdocument
- https://dom.spec.whatwg.org/#dom-document-createelement

So at the moment I don't see how this problem is related to or should be solved by changing how xmldom is adding the HTML namespace in html (and xhtml) documents.

Just an idea: Is it possible that the xpath library is not searching in the default namespace?

I will of course not dig into the code of the xpath library now. But if you have more information, that shows what xmldom is doing differently to cause this issue, feel free to reopen this github issue.

**Comment by sdeprez** [comment]
Thanks for your thorough answer! 

I agree on your analysis and that adding `xhtml` namespace is spec compliant. As per the specs you quoted, the issue here boils down to the fact that `[xpath](https://github.com/goto100/xpath)` strictly respects the xpath 1.0 specs but the browsers respect the `html` spec, which adds [a modification](https://html.spec.whatwg.org/#interactions-with-xpath-and-xslt) ("willful violation" as they say) to this spec to specifically handle that case, which got me confused.

**Comment by karfau** [comment]
Just for later reference/linking: Somebody just helped me to understand that @xmldom/xmldom@0.7.0 breaks the "HTML mode" detection of xpath, which was previously assuming `DOMImplementaiton.hasFeature` would return `false`: https://github.com/bbyars/mountebank/pull/660#issuecomment-1046606160
