### ISSUE TITLE
Package Size too large, Can I reduce it when use parseFromString only ?

### ISSUE THREAD

**Issue by suoyuesmile** [xmldom/xmldom#403]
![image](https://user-images.githubusercontent.com/22629276/165468740-834b4a4f-93ca-43e4-a8a0-c5a62a229d68.png)

**Comment by karfau** [comment]
`new DomParser().parseFromString` is one main entry points into the package.
It uses the SAX parser to create a DOM, which has all the methods to be serialized on its prototype.
So I don't see how you could save anything when only using that method.

May I ask what your criteria is for "too large"?
If you are targeting (only) a browser, just use the native API.
If you are targeting node or multiple runtimes,  you will most likely either not care about 20k or use a bundler that would be able to minify all included code, right?

That being said, we are currently not packaging a minified version of our package, since we do not have any build steps before publishing.
But since there are tolls like unpkg that offer this option, this shouldn't be to much of an issue.

Of course we are open for concrete suggestions/prs on this topic. Just be aware  that our releases are currently created "manually", see https://github.com/xmldom/xmldom/blob/master/docs/RELEASE.md
