### ISSUE TITLE
Uncaught ReferenceError: window is not defined

### ISSUE THREAD

**Issue by sauzy34** [xmldom/xmldom#424]
I'm using `xmldom` as a polyfill to enable DOM parser capabilities in the **Web Worker** environment. 
Using **browserify** file output in the `worker.js`

Here's my `dom-parser.js`
```
const { DOMParser } = require("@xmldom/xmldom");
window.DOMParser = DOMParser;
```

I'm using Webpack bundler to serve the web worker
```
const path = require("path");
const webpack = require("webpack");
const src = path.resolve(__dirname, "./src");
const build = path.resolve(__dirname, "./public"); // output worker.js to public folder

module.exports = {
  mode: "none",
  target: "webworker", // Important! Use webworker target
  entry: "./src/worker.js",
  output: {
    filename: "worker.js",
    path: build,
  },
  resolve: {
    modules: ["node_modules", src],
    extensions: [".js", ".json", ".jsx", ".ts", ".tsx"],
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify("development"),
    }),
  ],
  module: {
    rules: [
      {
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
        },
      },
    ],
  },
};

```

Getting error in `worker.js`

```
Uncaught ReferenceError: window is not defined
```

**Comment by karfau** [comment]
I'm not sure how we can help you.
The access to window is not coming from the code that xmldom provides:
https://github.com/xmldom/xmldom/search?q=window
So I would assume it comes from your dom-parser.js file.

I don't have any web worker experience, so I don't know how to solve your problem.
But maybe you can just import/require the DOMParser directly in your code and use it, instead of trying to add it to window?

I will close this ticket, since it is not related to xmldom itself.
In case you have more information that proves me wrong, please add it.

**Comment by sauzy34** [comment]
@karfau - I cannot directly use the DOM parser in the worker file because I'm using the AWS S3 SDK, which requires DOM parser as a depedency.

**Comment by karfau** [comment]
Well, that is whag wwbpack should take care of, putting all tge required code into a single fkle, right?
