### ISSUE TITLE
node.appendChild() alignment is improper

### ISSUE THREAD

**Issue by 2k177** [xmldom/xmldom#425]
```
import xml.dom.minidom

doc = xml.dom.minidom.parse("sample.xml")

build_info = doc.getElementsByTagName("build")

testElement = doc.createElement("build_tool")
testElement.setAttribute("name", "test1.log")
log_is_present = False
for build in build_info :
     if build .getAttribute("project") == "testing":
        for build_tool in build.getElementsByTagName("build_tool"):
            if "test1" in build_tool.getAttribute("path"):
                log_is_present = True
        if not log_is_present :
            build.appendChild(testElement)
xml_str = doc.toprettyxml(indent=" ", newl='')
with open("sample.xml", "w") as f:
     f.write(xml_str)
```
1. When the new element node is appended to "build" element, how to get it aligned properly like other childs of "build" element ?
Alignment is not inline with other child with above implementation.

2. if i use xml_str = doc.toprettyxml(), Many new lines are getting added in the xml file.

**Comment by karfau** [comment]
Thank you for creating the issue, but I don't understand what language/runtime your code should work in.
And I'm not sure you posted the issue in the right repository, since this lib is not minidom but the npm lib `@xmldom/xmldom`.

We also do not offer a method called `toprettyxml` (no matter which casing is applied), as far as I'm aware.

Closing it as invalid until I'm convinced otherwise.
