### ISSUE TITLE
Adding elements then serializing results in non-formatted text

### ISSUE THREAD

**Issue by Benjin** [xmldom/xmldom#44]
Parsing this XML:
```
<Parent>
    <FirstChild>
        <Grandchild />
    </FirstChild>
</Parent>
```

then appending a new child element to `Parent`, then serializing back to text results in this:

```
<Parent>
    <FirstChild>
        <Grandchild />
    </FirstChild>
<SecondChild><Grandchild /><SecondChild></Parent>
```

instead of the expected:

```
<Parent>
    <FirstChild>
        <Grandchild />
    </FirstChild>
    <SecondChild>
        <Grandchild />
    <SecondChild>
</Parent>
```

Is this expected?  Is there an option I can set somewhere to ensure serialized XML is human-readable/"pretty"?

**Comment by karfau** [comment]
Thank you for filing this and sorry that we have not been able to reply earlier, it must have slipped through somehow.

There is currently no option for pretty printing as part of the serialization, but the existing formatting of the input is preserved by also serializing the text nodes between the different elements. You could of course append the expected "text nodes" between the newly added elements to do something like pretty printing.

I'm not sure if it would be outside of the scope of this library to implement something like that, we should check how browser are treating this case.

At least we should come to a conclusion and properly document this before we reach 1.0

**Comment by Benjin** [comment]
My vote is for a pretty-print option!  Formatted XML is far easier to PR, so it's a common-enough case that saving me from having to find another library to handle that part of the serialization would be nice.

**Comment by karfau** [comment]
If you have to PR things then it's about stuff that you check into version control, so you could use one of the many tools available to prettify source code.
There are many different solutions possible, just to name a few:
- applying an XSLT transformation
- implementing a visitor that aligns text nodes in the tree so that nested elements are indented

They all boil down to inserting text nodes containing the required white space before or during serializing.

There are quite some things to consider like "what white space to use to indent?", "how to treat existing white space that doesn't match the space that should be used to use to indent?", ...

I'm not aware of any of [the specs we try to align with](https://github.com/xmldom/xmldom#specs) that has any related API/feature build in. So I do not think the current maintainers will invest time into this before 1.0

Feel free to post solutions/workarounds/proposals in this issue.
If you want to even provide a PR (including tests!) that offer formatting as an option, be aware that we might still reject it if we think we will not be able to maintain it.

**Comment by eamanola** [comment]
@karfau I can make a PR for this. do you have test documents?

**Comment by eamanola** [comment]
white space is indeed only workaround able, and might cause problem for some users.

**Comment by karfau** [comment]
@eamanola There are already quite some example documents in our tests and we even havea zip file full of documents, but I think it would be best to have a separate test suite with dedicated examples for this case, other wise we might just test to many things in a redundant manner

**Comment by eamanola** [comment]
@karfau here is a prettify proposal, with some basic tests. let me know what you think.

**Comment by karfau** [comment]
I just discovered that text nodes are not considered well formed as direct children of a document node. They are only allowed inside the root element:
https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity
This basically invalidates the approach of adding whitespace text nodes, at least between top level elements like processing instructions, comments, doctype and the root element.
The current plan is to fail parsing when such nodes would be present and also when trying to add them to the DOM, starting from v0.9.0 which we are currently working on.

@eamanola do you still plan to keep your PR updated? If you don't respond until I'm finalizing version 0.9.0, I will close your PR, since there are already conflicts.
