### ISSUE TITLE
Document.replaceChild fails

### ISSUE THREAD

**Issue by edemaine** [xmldom/xmldom#455]
**Describe the bug**
Since the 0.8.4 update, it's no longer possible to replace the (only) child of a document via `replaceChild`.

**To Reproduce**
https://stackblitz.com/edit/js-xmldom-template-3uxg9i?file=index.js

```js
const xmldom = require('@xmldom/xmldom');
const doc = new xmldom.DOMParser().parseFromString('<svg/>', 'image/svg+xml');
doc.replaceChild(doc.createElement('svg'), doc.firstChild);
```

**Expected behavior**
I expect the (only) child of the document to change, as this still respects the one-child rule for documents. Instead I get:

```
Uncaught Error: Not found: child not in parent
    at _insertBefore (C:\Users\edemaine\Projects\svgtiler\node_modules\@xmldom\xmldom\lib\dom.js:772:9)
    at Document.insertBefore (C:\Users\edemaine\Projects\svgtiler\node_modules\@xmldom\xmldom\lib\dom.js:908:3)
    at Document.replaceChild (C:\Users\edemaine\Projects\svgtiler\node_modules\@xmldom\xmldom\lib\dom.js:478:8) {
  code: 8
}
```

**Runtime & Version:**
xmldom version: 0.8.4 (doesn't occur on 0.8.3)
runtime version: Node v18.7.0
other related software and version: Windows 11

**Additional context**
A workaround is to remove the old child and then append the old child:

```js
doc.removeChild(doc.firstChild);
doc.appendChild(doc.createElement('svg'));
```

I also tested the following code in Chrome's `DOMParser`, and it works fine.

```js
const doc = new DOMParser().parseFromString('<svg/>', 'image/svg+xml');
doc.replaceChild(doc.createElement('svg'), doc.firstChild);
```

**Comment by pedro-l9** [comment]
I faced this same issue, upon some quick investigation it seems that it started on version 0.7.7 when there was a major change on dom.js, ever since the _insertBefore function no longer works as expected. The parent verification logic seems to be broken https://github.com/xmldom/xmldom/blob/fe5b043fd07bbfed7f039b77d0b9e1a1eb832a2a/lib/dom.js#L754

**Comment by edemaine** [comment]
I don't think it's the same reason, as my code worked in 0.8.3. I assume it has to do with the newly implemented "one child per document" rule.

**Comment by pedro-l9** [comment]
> 

Indeed I wasn't aware of such a rule, I stumbled into this error when using [Samlify](https://github.com/tngan/samlify), which uses xmldom internally. I mapped the issue to this point of Samlify's code:
https://github.com/tngan/samlify/blob/0950407d57bb1c5a93985a1d9b1bd2fd9182d1d5/src/libsaml.ts#L681

The condition that breaks is the one I mentioned previously when verifying the node's parent and it's the only place I could find in the code where the mentioned exception could be thrown. I mentioned version 0.7.7 because it was where this condition was added and from what I could experience 0.7.6 was the only version where I could get this operation to work. I don't know what might be happening to your code that makes it work with version 0.8.3.

Are you able to check if this condition exists in the version of the library that you're using and why it doesn't break?

**Comment by karfau** [comment]
Thank you both for the detailed information.
Both 0.7.7 and 0.8.4 received the same change, which 0.7.6 and 0.8.3 did not have.
I will prioritize fixing this issue.

**Comment by karfau** [comment]
Fix for this one is available in 0.9.0-beta.6. I will continue to work on the #456 before releasing the 0.8.x and 0.7.x versions.

**Comment by karfau** [comment]
Versions 0.7.9 and 0.8.6 have been released with a fix for this bug

**Comment by edemaine** [comment]
Thank you!  I confirm that 0.8.6 fixed both of my problems. With the now proper child detection, it even helped me find a bug in my code! 😅
