### ISSUE TITLE
Inconsistent "span" behavior

### ISSUE THREAD

**Issue by josecarlosrx** [xmldom/xmldom#467]
When we have two spans next to each other and one of them is not enclosed properly, the later span text is added as a sibling of the span instead of as a child. This happens because of the space in `</span >`

If we enclose it properly it all works well. The thing is that formatters add tabs to html tags when the string is large.

A fix could be to use `html.replace(/[\t\s]+\>/g, ">")` to scape whitespace on enclosing tags, but it would be nice for this to be fixed inside xmldom.
**To Reproduce**
https://stackblitz.com/edit/js-xmldom-template-cvnj8l?file=index.js

**Expected behavior**
We want the span text to be a child of span.

**Runtime & Version:**
xmldom version: 0.8.6 
runtime version: node 16.14.2
other related software and version: Windows 10

**Comment by karfau** [comment]
Thx for reporting this.
It seems to be related to #69, so I'm surprised to see this happen.
Will have to investigate.

**Comment by karfau** [comment]
This is a nasty one:
It seems to only happen for the last sibling tag with the same tag name, when it is different regarding "having the white space in the closing tag":

All of these work fine:
- `<xml><span>1</span ><span>2</span ></xml>` (first sibling also has space in closing tag)
- `<xml><span>1</span ><span>2</span></xml>` (only first has space)
- `<xml><span>1</span><span >2</span><span>3</span></xml>` (not the last one)
- `<xml><other>1</other><span>2</span ></xml>` (no sibling with the same name)

Needs more thorough investigation, so it might take more time then expected.
And there is a risk that it yields more issues...

**Comment by karfau** [comment]
I finally managed to look into this again, as part of #519 since the code I touched looked kind of related (and I was right).

I learned that the culprit is how "optional end tags" are currently "supported".
For reasons I don't fully understand yet, the current support causes this behavior, where unclosed tags are "magically self closing" and the content following it is appended to the DOM right afterwards.
I explains why only the last one is affected, since for that one it doesn't "find the closing tag" (not sure why).

I already invested some hours in finding a "minimal invasive" alternative approach without any luck.

Right now the linked PR would make the problem worse by wrongly detecting that the opening and closing tag names are not matching, because of the additional space, which is of course not an option, so I added a related test.

I will let you know what I was able to achieve once I'm there. :crossed_fingers:

**Comment by karfau** [comment]
I finally managed to look into this again, as part of #519 since the code I touched looked kind of related (and I was right).

I learned that the culprit is how "optional end tags" are currently "supported".
For reasons I don't fully understand yet, the current support causes this behavior, where unclosed tags are "magically self closing" and the content following it is appended to the DOM right afterwards.
I explains why only the last one is affected, since for that one it doesn't "find the closing tag" (not sure why).

I already invested some hours in finding a "minimal invasive" alternative approach without any luck.

Right now the linked PR would make the problem worse by wrongly detecting that the opening and closing tag names are not matching, because of the additional space, which is of course not an option, so I added a related test.

I will let you know what I was able to achieve once I'm there. :crossed_fingers:

**Comment by karfau** [comment]
I decided to drop the broken/incomplete "support" for unclosed/optional (end) tags in HTML in favour of more consistent behavior in XML.

It means that I consider the fix to be a breaking change, which will be part of 0.9.0 release (and the next pre-release with the `next` tag), which brings tons of other related breaking changes.

**Comment by karfau** [comment]
@josecarlosrx the fix was published as version 0.9.0-beta.11 (as the `next` tag).

Please let me know if all your cases are covered.
