### ISSUE TITLE
Trailing whitespace in processing instructions not preserved

### ISSUE THREAD

**Issue by shunkica** [xmldom/xmldom#497]
**Describe the bug**
Trailing whitespace in PI is not preserved.
One trailing whitespace is preserved if the PI does not have data.

**To Reproduce**
https://stackblitz.com/edit/js-xmldom-template-mcmkty?file=index.js

**Expected behavior**
The PI without data should have no trailing whitespace.
The trailing whitespace in PI with data should be preserved.
From [DOM Level 1 spec](https://www.w3.org/TR/REC-DOM-Level-1/level-one-core.html#ID-1004215813):

> Attributes
>     target
>         The target of this processing instruction. XML defines this as being the first token following the markup that begins the processing instruction.
>     data
>         The content of this processing instruction. **This is from the first non white space character after the target to the character immediately preceding the ?>.** 

**Runtime & Version:**
xmldom version: 0.8.8

**Comment by karfau** [comment]
Thank you for reporting the issue.
I think the culprit is in the regular expression in https://github.com/xmldom/xmldom/blob/master/lib/sax.js#L611, which seems to drop whitespace before the closing symbols.

Here is the same section in the DOM Level 2 spec: https://www.w3.org/TR/DOM-Level-2-Core/#core-ID-1004215813

But I still have to find the related part in the XML spec.

**Comment by karfau** [comment]
If I have to tackle it myself it will happen after I released 0.9.0, so there will be a patch for 0.8.x but not for 0.7.x

But if somebody else takes care of it before 0.9.0 is released 0.7.x will also be patched.
