### ISSUE TITLE
cpu 100% when parsing large partial xml

### ISSUE THREAD

**Issue by jseagull** [xmldom/xmldom#501]
**Describe the bug**
xmldom can parse the entire xml quickly, but parsing an xml fragment may take several minutes or even hours.

**To Reproduce**
```
const {DOMParser} = require('@xmldom/xmldom');
const {readFileSync} = require('fs');
const domParser = new DOMParser();
const xmlText = readFileSync('./big.xml').toString().slice(200)
domParser.parseFromString(xmlText, 'application/xml');
```

**Runtime & Version:**
xmldom version: 0.8.8 & 0.9.0-beta.8
runtime version: v16.19.0

**Additional context**

[big.xml.zip](https://github.com/xmldom/xmldom/files/11862846/big.xml.zip)

**Comment by karfau** [comment]
That's very interesting, since it's actually no longer supported to parse XML fragments (if we mean the same thing, I'm referring to an XML that has multiple root elements, see #458 ).
But of course it should be rejected and not run into an endless loop.
So thanks for the sample, I will have a look at it.

**Comment by karfau** [comment]
This sample really has some interesting things in it.
1. it's not a well-formed XML, even when it's read completely, here is a sample after removing MB of well formed elements inside `<rdf:Bag>` (The cursor is at the suggested position 200):
![image](https://github.com/xmldom/xmldom/assets/135657/27be21d4-265d-4463-b3e9-7fda94192ffb)

2. Even when parsing the whole document, xmldom only reports "error"s, which doesn't stop it from continuing parsing. I can only recommend to add an `errorHandler` that throws a `ParseError` on every reported `error` or even `warning`, especially when the documents are coming from user input.
3. If with "fragment" you expect that you can parse any arbitrary substring of an XML and expect it to return something useful: I have no clue how this is supposed to work, and the only reliable support that xmldom will ever offer is to properly throw (see point 2). Which doesn't happen for the sample you provided when starting at position 200.
   I know that there are some `while(true)` loops in the parsing code, so this will not be an easy one. But since this is related to not well-formed XML, it lower the priority of the task.

**Comment by jseagull** [comment]
I tested the code and found that the level parameter of the errorHandler is actually

```'[xmldom error]	element parse error: Error: elements closed character '/' and '>' must be connected to@#[line:undefined,col:undefined]'```

So it should be. 

```
const domParser = new DOMParser({errorHandler:(level) => {
  if (level.includes('xmldom error')) {
    throw new ParseError('stop parsing due to reported error');
  }
}});

```

**Comment by karfau** [comment]
Ah, you are right. since I changed it on master I confused how it worked before (which was quite complicated).
You can just add an `errorHandler` for `error`s by doing the following:
```
const domParser = new DOMParser({errorHandler:{error:() => {
  throw new ParseError('stop parsing due to reported error');
}}});
```
(but this will no longer work with versions >= 0.9.0-beta.9)

**Comment by mattiasw** [comment]
To make sure I understand this correctly, if the error handler gets an error there is no reason to continue parsing because that means xmldom won't find any valuable data in the XML that was passed in?

**Comment by karfau** [comment]
Well, there might be more "valuable data" (which I assume is the reason why it sometimes takes hours before finishing), but you should not rely on it, since it really depends on the error that is being reported.
The minimal criteria for reliably reading XML is that it is "well-formed", meaning the structure is properly nested, etc.
If that is not the case it basically isn't XML, it's just a string, so the code that adds data to the DOM after reporting such an error makes assumptions that might or might not be true...

Worst case it's might be a possible entry point for security issues.
And in the case that anybody is able to upload that data to your server ... being able to run a process for some hours might be considered a "denial of service" attack.

(In a future version most likely xmldom will most likely trigger a `fatalError` for all issues regarding well-formedness, but there is quite some work ahead to figure out which error should trigger what level.)

**Comment by karfau** [comment]
Since there has not been any report of this kind of issue with a different sample, I consider this issue "resolved by adding error handlers".
If any body is a ware of a sample that eats CPU even after adding an error handler please report it here or create a new issue.
Thank you
