### ISSUE TITLE
[feature-request] Any way to get "raw" node value without escaping? Or its absolute position?

### ISSUE THREAD

**Issue by Scratch-net** [xmldom/xmldom#506]
I have an arbitrary HTTP response and need to get **exact** start/end positions of arbitrary elements in this response using xPath.
After an element is found, I tried to do it by taking its string representation and doing a substring search. But because of escaping strings like `&` in attributes strings do not match and I'm not able to do it.
Parsing with 'text/html' mime type didn't help either

For reference, original element in response string looks like this:
```html
    <a class="a-link-normal" href="/ab/ref=title?ie=UTF8&asc=1">
        SOME Data Here
    </a>
```

and after serialization it looks like 

```html
    <a class="a-link-normal" href="/ab/ref=title?ie=UTF8&amp;asc=1">
        SOME Data Here
    </a>
```

I have lineNumber & columnNumber which are useless in this case, but is it possible to get an absolute position (and length) of an element in the original string, so that I wouldn't have to rely on string matching and serialization implementation? Or the original raw string without any alterings?

**Comment by karfau** [comment]
I'm not aware of a way to avoid the entity encoding, but I will double check. But we will most likely not implement a toggle to skip it if that is not already in place.

I would assume the line and column number are the location in the original string after normalizing whitespace, which should be a function that we either export already or could export (at least from one of the modules, but if needed even from the main export).

I also need to check if it is correct to replace the `&` with an `&amp;` in an attribute value, at first glance this doesn't look correct.

But one thing is for sure: xmldom is not roundtrip "safe" from the perspective you are trying it from. It always renders empty nodes as self-closed tags, so it is very unlikely that the line and column number make sense after serialization.

Is the snippet all you get or is it wrapped by other stuff?

**Comment by karfau** [comment]
Yes, for now. I will look into the questions I kisted things eventually, but I can not give any ETA.

So if you are able to look at the code on your own and find a way to achieve your goal without my support (based on the ideas/question in my first reply), you will most likely have an answer faster.

**Comment by shunkica** [comment]
I have not tested this at all, but this could be as simple as adding 

```
el.rawStart = tagStart;
el.rawLength = end - el.rawStart;
```

somewhere around line 163 in `sax.js`

However, I'm not sure if this is even a functionality that should be present.

**Comment by karfau** [comment]
> However, I'm not sure if this is even a functionality that should be present.

The more I think about it the more Im leaning into this direction:
the parser updates the information about the starting `line` and `column` to something called the `locator`, but this only indicates where something starts.

And there are multiple reason why that information is useless later on:
- The sax parser only ever receives the string that was returned by the `normalizeLineEndings` function, which can be passed as an option to the `DOMParser` constructor, by default it is this one: https://github.com/xmldom/xmldom/blob/48953f6e6d1d49093c8014c4585b31833de78812/lib/dom-parser.js#L40-L42
  so it could be overridden by a function that returns the string as is, or to not cause any parsing issues, keeps a reference of the result in a different place, so the indices could be used later
- https://github.com/xmldom/xmldom/blob/726b47117ae19e497a2c8c89908cc0bee7fb2e51/lib/sax.js#L237 changes the length of "some" attribute values
- all three usages of the entity replacer will convert entities in text content into the ctual characters, again changing the length of things https://github.com/xmldom/xmldom/blob/48953f6e6d1d49093c8014c4585b31833de78812/lib/sax.js#L54-L64

The only option that might work for XML nodes, but I would not want to rely on is to take the substring from the start position (where exactly that is needs to still be understood from the code that detects "new lines"), and hope that xmldom will correctly throw when encountering stuff after the "new root element"...

This whole locator stuff is so weird, and it's even active by default, causing tins of objects being copied while parsing and adding to the complexity in the code, I'm even tempted to drop it completely. I think the only purpose is to put a "rough" position for when it fails on things, which only happens when it';'s enabled...

Feel free to continue to discuss this, but I'm not going to invest any more time into this idea in the near future other than dropping the locator code from the parser.
