### ISSUE TITLE
Some entities in text content are not converted/escaped when serializing

### ISSUE THREAD

**Issue by cburatto** [xmldom/xmldom#58]
I have noticed that node values/strings containing `>` are not converted to `&gt;` when serializing the DOM. Is this due to any flag I should be using?

**Comment by karfau** [comment]
Did is the second > in your question written as `&gt;`? (Surround it with back ticks to prevent github from rendering it as >.)
If so:
I'm not aware of any "flags" that would change behavior of handling `>` in those cases.
I'm aware that xmldom is not doing that currently but (because I'm working on [restoring the tests](#35 )) I'm confident that the parsing is still correctly done.

I think having something that looks like a closing tag bracket in text or values is "uncritical" for XML parsers, which can not be said about `<` (these need to be converted for the parsing to work).

I have also seen that other parsers (at least one of the abandoned domjs or xmljs) treat those things in a more consistent manner.

If we would decide to change that (after having a stable test suite running on every change), even if it's not really a difference (from my current understanding) it might be considered a breaking change.

So my guess is such a change might not come very soon.

**Comment by cburatto** [comment]
Thanks -- I do mean a tag bracket character. For example, if a node value contains HTML text where entities have been converted. You load it with the DOMParser, then when you XMLSerialize it the entities are reconverted, except the closing bracket `>`

Example: 
`<xmlelement>&lt;b&gt;This is bold&lt;/b&gt;</xmlelement>`

gets serialized as
`<xmlelement>&lt;b>This is bold&lt;/b></xmlelement>`

**Comment by karfau** [comment]
Yes. That's what I was also referring to. But another short search in the old repo shows that there are already multiple issues around it there and also PRs.
I linked the "main thread" above.

**Comment by karfau** [comment]
@sarod Do I understand you correctly that you agree to a "subset" of the original question, namely for the case of `]]>` that needs to be converted to `]]%gt;`?

Do you think we should just always convert it, even thought he specification you are quoting also says (emphasis mine)

> The right angle bracket (>) **may** be represented using the string " &gt; ", and must, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.

?

I think I'm convinced that we should take care of the `]]>` case.
But for anything else I would love to see a failing test (either in a comment or as a PR or as link to any repo).

**Comment by karfau** [comment]
The only thing left to do here is to add (non standard) options to the serializer / `toString` methods to configure which characters to encode or not encode in different contexts. Which might need some discussions on how to implement it in a flexible and non breaking/disruptive manner.

But I don't consider this a very important feature compared to other topics.
(PRs with tests are of course welcome.)

**Comment by karfau** [comment]
There is some more related information in https://github.com/xmldom/xmldom/issues/22 which is the older one but I will still mark that one duplicate.

**Comment by sarod** [comment]
> @sarod Do I understand you correctly that you agree to a "subset" of the original question, namely for the case of `]]>` that needs to be converted to `]]%gt;`?
>
Yes.
 
> Do you think we should just always convert it?
The way I understand the xml spec is that outside of sequence ']]>' in a cdata content both '&gt;,' and '>' are valid. 

Limiting the conversion to the ']]>' case as the advantage of minimizing the changes in generated xml and so is likely to cause less breaking changes for consumers of the library. So that would be my recommendation but the choice is yours.

**Comment by karfau** [comment]
@sarod Thx for the clarification.
This change already landed on master: https://github.com/xmldom/xmldom/pull/181
and we are planning the next release https://github.com/xmldom/xmldom/milestone/3

This issue is left open just for the more general topic of controlling the general behavior of serializing entities, hence the changed title.

**Comment by SheetJSDev** [comment]
@karfau the spec seems to suggest that `>` must be encoded in `XMLSerializer#serializeToString`:

https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/ is the spec covering the method in question.

`XMLSerializer#serializeToString`: "[produce an XML serialization](https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/#dfn-concept-serialize-xml)"


step 5: Return the result of running the [XML serialization algorithm](https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/#dfn-concept-xml-serialization-algorithm)


step 14: Append to markup the result of the [XML serialization of node's attributes](https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/#dfn-concept-serialize-xml-attributes)

step 9.3: The result of [serializing an attribute value](https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/#dfn-concept-serialize-attr-value) given attr's [value](http://www.w3.org/TR/dom/#concept-attribute-value) attribute

step 3: Text:

"""

Otherwise, attribute value is a string. Return the value of attribute value, first replacing any occurrences of the following:

1. `"` with `&quot;`
2. `&` with `&amp;`
3. `<` with `&lt;`
4. `>` with `&gt;`

NOTE

This matches behavior present in browsers, and goes above and beyond the grammar requirement in the XML specification's AttValue production [[XML10](https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/#bib-XML10)] by also replacing ">" characters.
"""

The correct parsing of the spec is that [XML10](https://www.w3.org/TR/xml/) did not require `>` in attribute values to be escaped, but `XMLSerializer#serializeToString` does.

**Comment by karfau** [comment]
@SheetJSDev Thank you for digging deeper.

`<tagname attribute_key="attribute value">text content</tagname>`

But the lines you quote are talking about `attribute value`s, not `text content`.
But I also looked up those, and you are also right regarding `>`:
![image](https://user-images.githubusercontent.com/135657/161610745-5e16c522-0132-4e41-b599-f9d4ca4435a1.png)
(It's part of [this section](https://www.w3.org/TR/2016/WD-DOM-Parsing-20160517/#dfn-concept-xml-serialization-algorithm), but requires some scrolling.)

I will update the labels accordingly.

**Comment by SheetJSDev** [comment]
A bunch of issues related to `>` link here, so the conversation is confusion.  The deep dive concerns the following:

```js
new XMLSerializer().serializeToString(new DOMParser().parseFromString('<foo bar="&gt;"/>', 'text/xml').documentElement)
```

In Chrome:

```js
> new XMLSerializer().serializeToString(new DOMParser().parseFromString('<foo bar="&gt;"/>', 'text/xml').documentElement)
< '<foo bar="&gt;"/>'
```

In version 0.8.1:

```js
> const { XMLSerializer, DOMParser } = require("@xmldom/xmldom")
undefined
> new XMLSerializer().serializeToString(new DOMParser().parseFromString('<foo bar="&gt;"/>', 'text/xml').documentElement)
'<foo bar=">"/>'
```

**Comment by karfau** [comment]
You are right, it looks like I confused myself with all the different threads on this issue.
So far we only took care of `<`, `&` and whitespace in attributes and the special case of `]]>` in text content.

With the links you provided it makes sense to me that his is a bug and it will be fixed soon.

Thank you for insisting.

**Comment by karfau** [comment]
Using the master branch this issue should be resolved now.
Please let me know if it is not.
I will release 0.8.2 soon.

**Comment by SheetJSDev** [comment]
Looks good:

```
$ node -pe 'const { XMLSerializer, DOMParser } = require("@xmldom/xmldom"); new XMLSerializer().serializeToString(new DOMParser().parseFromString("<foo bar=\"&gt;\"/>", "text/xml").documentElement)'
<foo bar=">"/>
$ git clone --depth=1 https://github.com/xmldom/xmldom
$ cd xmldom
$ node -pe 'const { XMLSerializer, DOMParser } = require("./"); new XMLSerializer().serializeToString(new DOMParser().parseFromString("<foo bar=\"&gt;\"/>", "text/xml").documentElement)'
<foo bar="&gt;"/>
```
