### ISSUE TITLE
Depends on a deprecated dep resulting in a critical vulnerability issue on npm audit

### ISSUE THREAD

**Issue by Jonty16117** [xmldom/xmldom#599]
**Describe the bug**

On running npm audit it shows a critical vulnerability issue

**To Reproduce**
run `npm audit`

**Expected behavior**
There should be latest updated deps for it

**Runtime & Version:**
xmldom version: 0.8.10
runtime version: 18.17.1
other related software and version: 

**Additional context**
output:
```
xmldom  *
Severity: critical
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-5fg8-2547-mr8q
Misinterpretation of malicious XML input - https://github.com/advisories/GHSA-h6q6-9hqw-rwfv
xmldom allows multiple root nodes in a DOM - https://github.com/advisories/GHSA-crh6-fp67-6883
fix available via `npm audit fix --force`
Will install dom-compare@0.1.1, which is a breaking change
node_modules/xmldom
  dom-compare  >=0.2.0
  Depends on vulnerable versions of xmldom
  node_modules/dom-compare
```

**Comment by karfau** [comment]
The listed vulnerabilities have already been fixed in the latest version.

The report you linked already has a section called "How to fix" which explains the required steps in detail (besides that the package name is incorrect, it is @xmldom/xmldom).

This package does not have any `dependencies`, only `devDependencies` which are not relevant when installing it as a dependency.

According to the audit output you should upgrade the `dom-compare` package in your project.

If you have issues upgrading, feel free to use this thread to ask for support, but provide detailed information of what you have tried and what the resulting error/problem is.
