### ISSUE TITLE
Release of Verison 0.9.0

### ISSUE THREAD

**Issue by kboshold** [xmldom/xmldom#686]
Version "0.9.0-beta.11" has now been released for over a year. Are there any plans for when version 0.9.0 will be released? Are there any issues that still need to be resolved before the version can be released? 

Since version 0.9.0 contains a breaking change (errorHandler => onError), it should ideally be released as version 1.0.0.

**Comment by karfau** [comment]
Thx for asking/reminding me.
There have been some more changes that have been added to main since the last release, but I never managed to take the time to release those.
And since it has been a while since I did anything beside dependency updates, I do not remember what is in it.

I can not give an ETA, but I will try to make it happen.

Since the beta versions are pre-release versions, the next "real" release will be 0.9.0
And following that will be 0.10.0, since there are a lot of things missing before this could be called a "stable" release (as you can see in the milestones).

And the chances of this repo getting into that state are pretty low, since there are plenty of better options nowadays.
I will create a summary of those and guidance of when to use which in the readme.

**Comment by Ponynjaa** [comment]
Hey @karfau,
just wanted to ask if you can give a rough ETA on this?
Thanks :)

**Comment by karfau** [comment]
It is really hard for me do do that, but I understand that it's important.

I just revisited the dev.to post that I have written some time ago and updated it:
https://dev.to/karfau/upcoming-release-090-of-xmldomxmldom-2gnh-temp-slug-7213686?preview=f344d3e0b52fa43845f0551a105566d28fb5411a655f19f1817a7eb1113a902ad591028f68ccbce81119bffa18879c672aad39c5f247766ee1e834c9
(not sure how stable this link is, let me know if it no longer works)

I hope to be able to do it until next month, but for sure this year.

**Comment by karfau** [comment]
Thx for all the patience, finally managed to take the time.
