### ISSUE TITLE
Allow custom entityMap to be passed as DOMParser option

### ISSUE THREAD

**Issue by brodybits** [xmldom/xmldom#71]
The changes related to bug #57 (broken `&nbsp;` functionality), and lack of coverage of `lib/entities.js` detected by Stryker (see PR #70), got me thinking if we could import and reuse a better-tested implementation from npm. For example, with help from Google "npm html entities" & "npm xml entities":

- https://www.npmjs.com/package/html-entities
- https://www.npmjs.com/package/entities

and one step further to import SAX parser, as I suggested in #55?

**Addition by karfau**:

I think that we are currently quite clear that we do not want to introduce a dependency.

I think it would be worth while to allow users to override the entityMap (or a method that takes care of it) as an option for the DOMParser.
Currently xmldom applies different entity mapping for XML and HTML parsing which I think is not documented anywhere.

But of course we will also have to think about how it can be applied to serialization...

I'm aware that at least one downstream is reimplementing the replacement to apply it's mechanism before parsing with xmldom and after serialization, which is of course quite a tricky task and requires to wrap the XMLDOM API or play with the prototypes. We should just keep this in mind when implementing anything, so that similar approaches can reduce the amount of code they have to maintain.

**Comment by karfau** [comment]
I don't think it's a good reason to introduce a dependency.
Since we are currently trying to support ES5 without any build chain, we would need to find something that also supports that and make sure it doesn't stop doing that.
But it might still be worth investigating.
(I would recommend https://npms.io/search?q=html+entities and https://npms.io/search?q=entities as a starting point for research.)

**Comment by karfau** [comment]
I think that we are currently quite clear that we do not want to introduce a dependency.

I think it would be worth while to allow users to override the entityMap (or a method that takes care of it) as an option for the DOMParser. 
Currently xmldom applies different entity mapping for XML and HTML parsing which I think is not documented anywhere.

But of course we will also have to think about how it can be applied to serialization...

I'm aware that at least one downstream is reimplementing the replacement to apply it's mechanism before parsing with xmldom and after serialization, which is of course quite a tricky task and requires to wrap the XMLDOM API or play with the prototypes. We should just keep this in mind when implementing anything, so that similar approaches can reduce the amount of code they have to maintain.

**Comment by brodybits** [comment]
Makes sense to me, thanks.

+1 for user-pluggable method for entity mapping, thinking further if we could have a user-pluggable SAX parser?

**Comment by karfau** [comment]
Since we have landed #489 I will close this issue, since we now support all entities and according to the standard this list is fixed.

https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references
