### ISSUE TITLE
how to create document fragments from xml-code with prefixes

### ISSUE THREAD

**Issue by johanneswilm** [xmldom/xmldom#727]
Hey,
I have looked through what I could find of documentation and browsed through the source code, but I am not finding a solution to this anywhere.

Say I have an XML document parsed with xmldom. 

If the new child element doesn't use prefixed, it seems to be possible to create the child node like this:

```js
const childNode = parser.parseFromString('<title>...</title>', 'text/xml').lastChild

xmlDoc.lastChild.appendChild(childNode)
```

even if it has a different wonder document than the XML document it is being inserted into.

However, if the syntax of the child node uses prefixes, an error is thrown when trying to parse the XML fragment:

```js
const childNode = parser.parseFromString('<dc:title>...</dc:title>', 'text/xml').lastChild
 ...
 ```
 
 Is there some way to turn that error message off or to achieve the same thing in some other way?

**Comment by Ponynjaa** [comment]
Hey @johanneswilm,
it is actually correct that an error is thrown when you try to parse a document containing namespace prefixes but no namespace definition. You need to define the namespace for the prefix `dc` in this case. It could look like this:
```js
parser.parseFromString('<dc:title xmlns:dc="your/namespace"/>', 'text/xml')
```

You can even try this in the browser console:
```js
new DOMParser().parseFromString('<dc:title/>', 'text/xml')
```
This will throw an Exception, just like xmldom.

Your first case works since it uses the default namespace which is always there. You could override the default namespace like this:
```js
parser.parseFromString('<title xmlns="your/namespace"/>', 'text/xml');
```

**Comment by johanneswilm** [comment]
Hey @Ponynjaa ,
yes, I know that it throws in the browser. But the browser throwing errors constantly (both when that is correct and when there is a bug in the browser) is the main reason I am now trying to do work with a JavaScript library instead. I had hoped that I could turn of these kind of validity checks as in my case they are just a waste of time.

Also, in the browser I can inject code inside an XML document doing something like:

```js

xmlCodeElement.innerHTML = "<dc:title></dc:title>"
```

or 

```js
xmlCodeElement.inderAdjacentHTML('afterbegin', "<dc:title></dc:title>")
```

None of which is possible with xmldom. Correct?

So there is no way of doing this then? Declaring every single name space every time is not an option for me (having xmldom check this for no good reason every time is also eating processing power in a way I am not OK with).

**Comment by karfau** [comment]
> yes, I know that it throws in the browser. But the browser throwing errors constantly (both when that is correct and when there is a bug in the browser) is the main reason I am now trying to do work with a JavaScript library instead. I had hoped that I could turn of these kind of validity checks as in my case they are just a waste of time.

There is no way to "turn off" these checks, since this is how xml with namespaces is defined to work.
Anything else doesn't make sense from a security perspective.

But with xmldom there is one more option to declare namespaces that are present in your xml:

```
new DOMParser({
  xmlns: {
    'dc':'the/namespace/uri',
    '':'the/default/namespace',//optional
  }
}).parseFromString(...)
```

> Also, in the browser I can inject code inside an XML document doing something like:
> 
> ```js
> xmlCodeElement.innerHTML = "<dc:title></dc:title>"
> ```
> 
> or 
> 
> ```js
> xmlCodeElement.inderAdjacentHTML('afterbegin', "<dc:title></dc:title>")
> ```
> 
> None of which is possible with xmldom. Correct?

Yes, this is correct, since xmldom currently doesn't implement these properties/methods 

> So there is no way of doing this then? Declaring every single name space every time is not an option for me (having xmldom check this for no good reason every time is also eating processing power in a way I am not OK with).

You might be able to find a different "xml" library that ignores the restrictions that come with  xml namespaces and just parses them without checking them. But this is not something xmldom is going to implement.

**Comment by johanneswilm** [comment]
Ok, thanks for the information. If I wanted an xml parser that is unforgiving and cannot be customized, I'd just use the one build into the browser. 
I guess something like fast-xml-parser plus creating my own dom operations should work.
If it doesn't, I'll just make my own fork of xmldom and comment out those checks.
