### ISSUE TITLE
getElementsByTagName returns wrong type in 0.9.2

### ISSUE THREAD

**Issue by sserdyuk** [xmldom/xmldom#731]
**Describe the bug**

Prior to 0.9.X `getElementsByTagName` returned a properly typed collection. Now it returns a `LiveNodeList` that doesn't infer element type from the search and types to `(Node | undefined)[]` with `Array.from()`.
As the result, in the following code, the `image.getAttribute` part gives two compilation errors. THe first is given because `image` can be undefined, the second one is because `getAttribute` is not defined on `Node` even though it actually is `HTMLImageElement`.

```
const headerDoc = new DOMParser().parseFromString(
        `<!DOCTYPE html> <html lang="en"> <body>${headHtml}</body></html>`,
        'text/html',
      ),
      images = headerDoc.getElementsByTagName('img'),
      logoImage =
        Array.from(images).find((image) => image.getAttribute('id') === 'logo') ??
        Array.from(images).find((image) => image.getAttribute('alt') === 'Logo');
```
I am not sure what was the intent with the change but it completely messed us up, and I don't see a way to rewrite the code in any working way. We're staying back on 0.8.10 for now.

**Expected behavior**
As in 0.8.10, `headerDoc.getElementsByTagName('img')` should return a property typed collection like `HTMLCollectionOf<HTMLImageElement>`

**Runtime & Version:**
xmldom version:  0.9.2 & 0.8.10
runtime version: Node v18.20.4
typescript: 5.6.2

**Comment by wydengyre** [comment]
@sserdyuk FWIW this is fine on 0.9.0 for me. The problem seems to have been introduced in a patch release 😢

**Comment by karfau** [comment]
Thx for the report.
Just to be clear:
The implementation dudn't chabge, "only" the types changed to what xmldom actually supported all the time.

Since I vendored the types from typescript and there are plenty of things that xmldom doesn't support I went for throwing out the thousands of overloads and the generics.
By using something like `@xmldom/is-dom-node` you should be able to typecheck the nodes to element types.

But I understand that it can be considered a breaking change and I will have to investigate how much effort it will be to restore all the generic overloads.

**Comment by karfau** [comment]
OK, so I just read the original post again (not on the phone this time) and I think I misunderstood it the first time I read it.

I agree that the code you present should work, because `getElementsByTagName` should return something related to `Element`s. And also the potential `undefined` gets in the way here, and was indeed a change I introduced without considering the implications well enough.

Just to be explicit: xmldom will not provide an `HTMLImageElement` type of overload or even [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) because there are no plans to implement all of the properties. But this is not the issue causing problems in the code you presented.

**Comment by sserdyuk** [comment]
@karfau Thank you for looking into it again. Just to be clear, the part where I described the method returning a collection of HTMLImageElement elements is how it already worked in 0.8.10. I'm not asking for any new functionality.

**Comment by karfau** [comment]
Yes, it "worked" that way because you only used the part of the previously returned types that existed in the implementation.
If you would have tried to use any `HTMLEkement` (like `.title` or `.style`) or `HTMLImageElement` (like `.src` or `.alt`) only attribute, it would not have worked aka returned `undefined`.

The same is true for the `HTMLCollection` regarding it's named items access.

Now the types tell the truth of the implementation, previously they were imposters.

**Comment by karfau** [comment]
> FWIW this is fine on 0.9.0 for me. The problem seems to have been introduced in a patch release 😢 

The types since 0.9.0 are broken in different was, I'm sorry about the mess, and working hard to recover the cases that the current implementation supports.
