### ISSUE TITLE
error when text contains 'zwsp' 

### ISSUE THREAD

**Issue by nkbai** [xmldom/xmldom#767]
**Describe the bug**
cannot find element pay-button-sdk:

**To Reproduce** 
**Expected behavior**
```
    it("zwsp", () => {
        const xmlData = ` 
      <view class="fs16 dark medium {{true?'red':'blue'}}">
 
        <pay-button-sdk   ​  
          order-status="{{1}}"  >
        </pay-button-sdk>
      </view>
       
`;

        var DOMParser = require('xmldom').DOMParser;

        var xmlStringSerialized: Document = new DOMParser().parseFromString(xmlData, "text/xml");
        var tags = xmlStringSerialized.getElementsByTagName('pay-button-sdk')
        expect(tags.length).toBe(1)
    })
``` 
expect tags.length is 1, but got 0
**Runtime & Version:**
xmldom version: 0.5.0
runtime version: nodejs: v18.20.4
other related software and version: 

**Additional context**
![image](https://github.com/user-attachments/assets/cf1e4b6e-421b-41e7-a3ab-0ac5c8f442b6)
there is a hidden charactar 'zwsp' in the xmlData

**Comment by karfau** [comment]
Thx for the report.
Version 0.5.0 of xmldom is no longer supported.
Can you test it with a 0.8.* or 0.9.* version of `@xmldom/xmldom`?

**Comment by nkbai** [comment]
for the latest version: 0.9.0, report another error:
```
Opening and ending tag mismatch: "view" != "pay-button-sdk"
ParseError: Opening and ending tag mismatch: "view" != "pay-button-sdk"
```

```
    it("zwsp", () => {
        const xmlData = ` 
      <view class="fs16 dark medium {{true?'red':'blue'}}">
 
        <pay-button-sdk   ​  
          order-status="{{1}}"  >
        </pay-button-sdk>
      </view>
       
`;
        var xmlStringSerialized: Document = new DOMParser().parseFromString(xmlData, MIME_TYPE.XML_TEXT);
        var tags = xmlStringSerialized.getElementsByTagName('pay-button-sdk')
        expect(tags.length).toBe(1)
    })
```
it seems that xmldom doesn't handle 'zwsp' correctly.

**Comment by karfau** [comment]
Thank you for checking that.

I will check why that is the case.

For the time being, it would be a workaround to replace the character with a space or the empty string before sending the xml string to  `parseFromString`.

**Comment by karfau** [comment]
So, here is what I found:
Not even the DOMParser implementation in a browser will parse your input without errors:
![image](https://github.com/user-attachments/assets/c4c5221c-d7a6-4d67-83b2-24bef5187029)
this is because the [`U+200B`/`&zwsp;` charachter](https://en.wikipedia.org/wiki/Zero-width_space) in your input is not allowed between attributes or as part of attribute names, according to the XML specification:
- https://www.w3.org/TR/xml11/#NT-S
- https://www.w3.org/TR/xml11/#NT-Name

(It is of course allowed as part of the content of attributes or as text content within/between text, but in those places it will be replaced with with the related HTML entity when you parse and serialize a document containing it in a valid position using xmldom.)
