### ISSUE TITLE
How to ignore error for the Unicode replacement character?

### ISSUE THREAD

**Issue by eglitise** [xmldom/xmldom#790]
I would like to know if it is possible to configure `DOMParser` to not raise an error for the Unicode replacement character.
Up until `0.9.0`, `@xmldom/xmldom` was parsing this character like any other, until #519 changed it to throw an error.

Looking at the README, it seems possible to configure error handling using `DOMParser`'s `onError` option, but (if I understand it correctly), this does not apply to fatal errors, which unfortunately is the case here.

I also couldn't find any mentions of this character in the W3C API reference, so I assume this behavior is not standard.

Original issue: https://github.com/appium/appium-inspector/issues/1729

**Comment by karfau** [comment]
Is there a way to look at the exact document string that is being parsed?
I would like to understand what the use case is for having such a character in the document.
Is it escaped in some way?
There were multiple issues around it and all of them boiled down to wrong encoding when reading/transforming the data if I remember correctly.

I will double check why and how we exclude it. And if the conclusion is tgat we need to be able to opt-in to skip that check, it should hopefully be possible to do that.

**Comment by eglitise** [comment]
@karfau - thanks for the response.
In my case the document is the XML source of a mobile application screen. I am not in any control whatsoever over the contents of this XML, but I do believe it should still be valid in all other respects (i.e. no mismatched/unclosed tags and the like). My application is simply converting this source to a user-readable and interactable format.

One example for an XML I expect to be parsed without issues is the Wikipedia page for Mojibake: https://en.wikipedia.org/wiki/Mojibake. It works fine in 0.8.10 but returns an error in 0.9.5.
Here's a Gist of the retrieved XML: https://gist.github.com/eglitise/ee16b7de7d6df1df2b37e6133dba5262
Here's a screenshot of how it looks like on the mobile device:
![appium-inspector-2024-11-22T14_57_13 518Z](https://github.com/user-attachments/assets/f3033248-9470-4b65-a6e7-a8df59164a9f)

**Comment by karfau** [comment]
I needed some time to dig deeper.
I also didn't find any source that says that these character are not allowed.
The thing that lead me to treat those character special are three test cases in our test suite, which claim that the following document is not well-formed:
`<doc>�</doc>`, but I have no clue why that would be the case.
I will try and ask the author of these files to understand the reasoning, but I'm not sure I will get an answer soon.

I think it is more aligned with the specs I'm aware of, to not raise this as a `fataError`. Since it is still very likely be a an encoding issue, my suggestion would be to lower the level to a `error` or `warning` or `error`. My current tendency would be `warning` since we can not know if the document contains this character intentionally or not.
This way the strictest mode you can opt in from error handling would still not allow it, but by default you are able to ignore it.

What do you think?

And I still have to decide if any of that would be considered a breaking change

**Comment by eglitise** [comment]
Thanks - I fully agree that the `warning` level would probably be the best choice here.

**Comment by karfau** [comment]
@eglitise Do you have a way of testing the fix in #794 on your side before it lands?

**Comment by eglitise** [comment]
@karfau thanks so much for the quick fix! 🙏
I tested it using patch-package just now (just the change in `sax.js`), and the replacement character is now being parsed without issues, as expected 🙂

**Comment by karfau** [comment]
Nice, I will take care of the release within this week.

**Comment by karfau** [comment]
0.9.6 is finally released

**Comment by eglitise** [comment]
Thank you!
